global:
  env:
    - DATA_ARCHIVE=data.tar.gz
    - ARCHIVE_ID=$TRAVIS_BUILD_NUMBER
jobs:
  include:
    - stage: analyze_data
      dist: xenial
      language: python
      python:
        - 3.7.2
      cache:
        - pip
      install:
        - pip install -r scripts/requirements.txt
        - mkdir -p build/data
      script:
        - bin/build-data-analysis.sh
        - tar -czvf build/$DATA_ARCHIVE build/data/*
        - bin/upload-build-archive.sh build/$DATA_ARCHIVE $ARCHIVE_ID

    - stage: build_website
      language: php
      php:
        - 7.3
      install:
        - bin/s3/download-archive.sh $DATA_ARCHIVE $ARCHIVE_ID > build/$DATA_ARCHIVE
        - cd build/ && tar -xvsf $DATA_ARCHIVE
      script:
        - ls -la build/
        - bin/build-website.sh
        - rm -rf build/*.gz build/*.csv
        - bin/s3/delete-archive.sh $DATA_ARCHIVE $ARCHIVE_ID

      deploy:
        if: branch = master
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        verbose: true
        local_dir: site/build_production/
        env:
          - ENV=BUILD
        on:
          branch: master

stages:
  - analyze_data
  - build_website
