script:
  - bash bin/build/initialize.sh
  - bash bin/build/prepare-raw-data.sh
  - bash bin/build/generate-sqlite-bases.sh
  - bash bin/build/clean.sh
  - bash bin/build/compile-website.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  verbose: true
  on:
    branch: master

