script:
  - bash bin/build/initialize.sh
  - bash bin/build/prepare-raw-data.sh
  - bash bin/build/generate-sqlite-bases.sh
  - bash bin/build/join-all-sqlite-bases.sh
  - bash bin/build/extract-deputies.sh
  - bash bin/build/clean.sh
  - npm run prepare-deployment
  - rm -rf build/*.db

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  verbose: true
  env:
    - ENV=BUILD
  on:
    branch: master
