language: php
php:
  - 7.3

script:
  - bash bin/fetch-raw-data.sh
  - bin/build-data-analysis.sh
  - bin/build-website.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  verbose: true
  local_dir: site/build_production/
  env:
    - ENV=BUILD
  on:
    branch: master
