language: php
php:
  - 7.3
python:
  - 3.7.2

install:
  - pip install -r scripts/requirements.txt

script:
  - python scripts/test-pandas.py

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  verbose: true
  local_dir: site/build_production/
  env:
    - ENV=BUILD
  on:
    branch: master
