script:
  - bin/fetch-raw-data.sh
  # - bin/build-data-analysis.sh
  # - bin/build-website.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  verbose: true
  env:
    - ENV=BUILD
  on:
    branch: master
