env:
  global:
    - DATA_ARCHIVE=data.tar.gz
    - ARCHIVE_ID=$TRAVIS_BUILD_NUMBER
jobs:
  include:
    - stage: analyze_data
      dist: xenial
      language: python
      python:
        - 3.7.2
      cache:
        - pip
      install:
        - pip install -r scripts/requirements.txt
        - mkdir -p build/data
      script:
        - bin/fetch-raw-data.sh
        - bin/build-data-analysis.sh
        - rm -rf build/raw-data
        - tar -czvf build/$DATA_ARCHIVE build/*
        - bin/s3/upload-archive.sh build/$DATA_ARCHIVE $ARCHIVE_ID

    - stage: build_website
      language: php
      php:
        - 7.3
      install:
        - mkdir -p build/data
        - bin/s3/download-archive.sh $DATA_ARCHIVE $ARCHIVE_ID > build/$DATA_ARCHIVE
        - tar -xvsf build/$DATA_ARCHIVE
        - bin/s3/delete-archive.sh $DATA_ARCHIVE $ARCHIVE_ID
      script:
        - bin/build-website.sh

      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        verbose: true
        local_dir: site/build_production/
        env:
          - ENV=BUILD
        on:
          branch: test_python_env

stages:
  - analyze_data
  - build_website
